INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, CATEGORY, STOCK, RATING, IMAGE_URL, CREATED_AT, UPDATED_AT)
VALUES (1, 'Laptop', 'High performance laptop', 799.99, 'Electronics', 10, 4.5, 'img1.png', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
